version: '2'
services:
    jhips201805-app:
        image: jhips201805
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://jhips201805-mysql:3306/jhips201805?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    jhips201805-mysql:
        extends:
            file: mysql.yml
            service: jhips201805-mysql
